name: Gitleaks Secret Scan

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (CLI)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            ghcr.io/gitleaks/gitleaks:latest \
            detect \
            --source=/repo \
            --verbose \
            --redact \
            --exit-code 1
